### ISSUE TITLE
usePersist not found

### ISSUE THREAD

**Issue by juanmanavarro** [quarrant/mobx-persist-store#1]
`export 'usePersist' was not found in 'mobx-persist-store'`

Thanks.

**Comment by quarrant** [comment]
> `export 'usePersist' was not found in 'mobx-persist-store'`
> 
> Thanks.

Thank you! It's my mistake. `usePersist` had an architecture error and i deleted it from export, but i forget to update Readme.

Instead of `userPersist` you can use `@persistence` decorator. 

```ts
@persistence({
  name: 'MyStore',
  properties: ['servicesCatalog'],
  adapter: new StorageAdapter({
    write: FsService.writeJsonFile,
    read: FsService.readJsonFile,
  }),
})
export default class MyStore {}
```

**Comment by quarrant** [comment]
fixed
