### ISSUE TITLE
Question: Is it possible to persist multiple instances of a store without separately naming them?

### ISSUE THREAD

**Issue by ThaJay** [quarrant/mobx-persist-store#109]
Example:

- I have a WidgetStore
- I have a ChosenWidgetsStore
- I want to persist ChosenWidgetsStore AND each instance of WidgetStore

How would this work?

At the moment I may be able through some finaggling save WidgetStore instances on ChosenWidgetsStore

But what if I don't have the instances in a store? What if I have a bunch of Widget components who all have their own WidgetStore? I could use some kind of string passed in the constructor and add it to the `name` to make it unique.

What if I don't have that kind of information or don't want my instanced stores to have that kind of information because of dependencies and decoupling?

We already give `this` to `makePersistable`. So we could already identify an instance in memory by checking with triple equality. Would it also be possible to do something like this for persisted stores? Where `makePersistable` has information about the actual instance that called it?
If possible this could also make the `name` property obsolete.

Let me know your thoughts.

**Comment by quarrant** [comment]
Soooo. It's really hard to persist recursive trees and I don't know how soon we can do it. You would better writing your own solution

**Comment by ThaJay** [comment]
Thank you for your answer. Perhaps I should start reading about Mobx State Tree again.
