### ISSUE TITLE
configurePersistable initialization failed？

### ISSUE THREAD

**Issue by momtboy** [quarrant/mobx-persist-store#114]
index.ts:8 mobx-persist-store: GlobalStore does not have a valid storage adaptor.

* Make sure the storage controller has 'getItem', 'setItem' and 'removeItem' methods."

**Comment by momtboy** [comment]
`configurePersistable({
  storage: window.localStorage,
  debugMode: true,
})`

**Comment by quarrant** [comment]
Hello! I think you need something like this https://github.com/quarrant/mobx-persist-store/issues/91

**Comment by codeBelt** [comment]
@momtboy It's has been awhile but if you are using `storage: window.localStorage` I think you also need to set `stringify: true`. I could be wrong.

`configurePersistable({ storage: window.localStorage, stringify: true, debugMode: true, })`
