### ISSUE TITLE
Cant persist more than one store

### ISSUE THREAD

**Issue by rendomnet** [quarrant/mobx-persist-store#12]
I have several stores made by this example.

And only one store persist. Other-ones don't even shows in LocalStorage.
They call same readStore, writeStore functions.

They have different names and working but do not persist.

`
import { makeAutoObservable } from 'mobx';
import { persistence, useClear, useDisposers, isSynchronized, StorageAdapter } from 'mobx-persist-store';

function readStore(name) {
  return new Promise((resolve) => {
    const data = localStorage.getItem(name);
    resolve(JSON.parse(data));
  });
}

function writeStore(name, content) {
  return new Promise((resolve) => {
    localStorage.setItem(name, JSON.stringify(content));
    resolve();
  });
}

class CounterStore {
  counter: number = 0;

  tickCounter = () => {
    this.counter = this.counter + 1;
  };

  constructor() {
    makeAutoObservable(this);
  }
}

export default persistence({
  name: 'CounterStore',
  properties: ['counter'],
  adapter: new StorageAdapter({
    read: readStore,
    write: writeStore,
  }),
  reactionOptions: {
    // optional
    delay: 2000,
  },
})(new CounterStore());
`

**Comment by quarrant** [comment]
The name property must be unique
```js
persistence({ name: 'store 1', ... })
persistence({ name: 'store 2', ... })
persistence({ name: 'store 3', ... })
```

example - https://codesandbox.io/s/fervent-sound-m7ie5?file=/src/App.tsx
