### ISSUE TITLE
Usage with TypeScript?

### ISSUE THREAD

**Issue by deadcoder0904** [quarrant/mobx-persist-store#14]
I tried converting the Mobx 6 example to TypeScript.

I modified 2 lines (one in `readStore` & another in `writeStore` which you can compare with https://github.com/quarrant/mobx-persist-store#with-mobx-6) to solve TS errors but that caused other 2 errors:

```tsx
import {
	persistence,
	useClear,
	useDisposers,
	isSynchronized,
	StorageAdapter,
} from 'mobx-persist-store'

import { CounterStore } from '@/store/index'

function readStore(name: string) {
	return new Promise((resolve) => {
		const data = localStorage.getItem(name) || '{}'
		resolve(JSON.parse(data))
	})
}

function writeStore(name: string, content: string) {
	return new Promise((resolve) => {
		localStorage.setItem(name, JSON.stringify(content))
		resolve(null)
	})
}

export default persistence({
	name: 'CounterStore',
	properties: ['counter'],
	adapter: new StorageAdapter({
		read: readStore,
		write: writeStore,
	}),
	reactionOptions: {
		// optional
		delay: 2000,
	},
})(new CounterStore())
```

I am getting an error on `read` & `write` properties in `persistence`.

Here's the error on `read`:

> (property) read: (name: string) => Promise<string | undefined>
Type '(name: string) => Promise<unknown>' is not assignable to type '(name: string) => Promise<string | undefined>'.
  Type 'Promise<unknown>' is not assignable to type 'Promise<string | undefined>'.
    Type 'unknown' is not assignable to type 'string | undefined'.
      Type 'unknown' is not assignable to type 'string'.ts(2322)
types.d.ts(16, 5): The expected type comes from property 'read' which is declared here on type 'StorageAdapterOptions'

How can I solve it?

**Comment by deadcoder0904** [comment]
I solved it for `readStore` but do check if I'm correct:

```tsx
function readStore(name: string) {
	return new Promise<string>((resolve) => {
		const data = localStorage.getItem(name) || '{}'
		resolve(JSON.parse(data))
	})
}
```

But can't get it right for `writeStore`.

> (property) write: (name: string, value: string) => Promise<Error | undefined>
Type '(name: string, content: string) => Promise<unknown>' is not assignable to type '(name: string, value: string) => Promise<Error | undefined>'.
  Type 'Promise<unknown>' is not assignable to type 'Promise<Error | undefined>'.
    Type 'unknown' is not assignable to type 'Error | undefined'.
      Type 'unknown' is not assignable to type 'Error'.ts(2322)
types.d.ts(15, 5): The expected type comes from property 'write' which is declared here on type 'StorageAdapterOptions'

How do I do it?

**Comment by deadcoder0904** [comment]
I think I solved it but lmk if it's correct or not as I'm a TS noob but I see no errors now:

```tsx
import {
	persistence,
	useClear,
	useDisposers,
	isSynchronized,
	StorageAdapter,
} from 'mobx-persist-store'

import { FrameItStore } from '@/store/index'

function readStore(name: string) {
	return new Promise<string>((resolve) => {
		const data = localStorage.getItem(name) || '{}'
		resolve(JSON.parse(data))
	})
}

function writeStore(name: string, content: string) {
	return new Promise<Error | undefined>((resolve) => {
		localStorage.setItem(name, JSON.stringify(content))
		resolve(undefined)
	})
}

export default persistence({
	name: 'FrameItStore',
	properties: ['counter'],
	adapter: new StorageAdapter({
		read: readStore,
		write: writeStore,
	}),
	reactionOptions: {
		// optional
		delay: 2000,
	},
})(new FrameItStore())
```

**Comment by deadcoder0904** [comment]
I think I solved it but lmk if it's correct or not as I'm a TS noob but I see no errors now:

```tsx
import {
	persistence,
	useClear,
	useDisposers,
	isSynchronized,
	StorageAdapter,
} from 'mobx-persist-store'

import { CounterStore } from '@/store/index'

function readStore(name: string) {
	return new Promise<string>((resolve) => {
		const data = localStorage.getItem(name) || '{}'
		resolve(JSON.parse(data))
	})
}

function writeStore(name: string, content: string) {
	return new Promise<Error | undefined>((resolve) => {
		localStorage.setItem(name, JSON.stringify(content))
		resolve(undefined)
	})
}

export default persistence({
	name: 'CounterStore',
	properties: ['counter'],
	adapter: new StorageAdapter({
		read: readStore,
		write: writeStore,
	}),
	reactionOptions: {
		// optional
		delay: 2000,
	},
})(new FrameItStore())
```

**Comment by deadcoder0904** [comment]
I see an error in the DevTools Console now at `JSON.parse` even though it is `string` already:

> SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.JSONParse (chrome-extension://debbgbhhohmjgdmndiakoejhjdggnigc/popup.js:41305:20)
    at chrome-extension://debbgbhhohmjgdmndiakoejhjdggnigc/popup.js:41012:47

Not sure how to solve it?

**Comment by deadcoder0904** [comment]
This solved it but it was too much trouble:

```tsx
function readStore(name: string) {
	return new Promise<string>((resolve) => {
		const data = localStorage.getItem(name)
		if (typeof data === 'string') resolve(JSON.parse(data))
		resolve('{}')
	})
}
```

I am unable to get the state stored in the local storage even though I point now to the `persistence` object.

**Comment by quarrant** [comment]
it will be correct

```ts
function readStore(name: string) {
	return new Promise((resolve) => {
		const data = localStorage.getItem(name) || '{}'
		resolve(data)
	})
}

function writeStore(name: string, content: string) {
	return new Promise((resolve) => {
		localStorage.setItem(name, JSON.stringify(content))
		resolve(undefined)
	})
}
```

**Comment by deadcoder0904** [comment]
Nope, it gives error inside `persistence` in VSCode.

![mobx-persist-store](https://user-images.githubusercontent.com/16436270/107504126-dbc5d380-6bc0-11eb-8500-3b906fb58898.png)

On `read`, it gives:

> (property) read: (name: string) => Promise<string | undefined>
Type '(name: string) => Promise<unknown>' is not assignable to type '(name: string) => Promise<string | undefined>'.
  Type 'Promise<unknown>' is not assignable to type 'Promise<string | undefined>'.
    Type 'unknown' is not assignable to type 'string | undefined'.
      Type 'unknown' is not assignable to type 'string'.ts(2322)
types.d.ts(16, 5): The expected type comes from property 'read' which is declared here on type 'StorageAdapterOptions'

On `write`, it gives:

> (property) write: (name: string, value: string) => Promise<Error | undefined>
Type '(name: string, content: string) => Promise<unknown>' is not assignable to type '(name: string, value: string) => Promise<Error | undefined>'.
  Type 'Promise<unknown>' is not assignable to type 'Promise<Error | undefined>'.
    Type 'unknown' is not assignable to type 'Error | undefined'.
      Type 'unknown' is not assignable to type 'Error'.ts(2322)
types.d.ts(15, 5): The expected type comes from property 'write' which is declared here on type 'StorageAdapterOptions'

Someone on StackOverflow said that the type of `Promise` is `unknown` like `Promise<unknown>` so you have to explicitly specify it.

So typing the type in `Promise` solves it:

![correct version](https://user-images.githubusercontent.com/16436270/107504559-7faf7f00-6bc1-11eb-9037-65719541b24b.png)

Didn't need `JSON.parse` there.

Also, would love to know if I'm using it correct as there is nothing in Local Storage. Earlier, I used to do:

```tsx
import { FrameItStore } from '@/store/FrameItStore'
import { PersistState } from '@/store/PersistState'
import { FrameItProvider, FrameItContext, useFrameItStore } from '@/store/FrameItContext'

const stores = {
	frameitStore: new FrameItStore(),
}

export { stores, FrameItStore, FrameItProvider, FrameItContext, useFrameItStore }
```

And now I do:

```tsx
import { FrameItStore } from '@/store/FrameItStore'
import { PersistState } from '@/store/PersistState'
import { FrameItProvider, FrameItContext, useFrameItStore } from '@/store/FrameItContext'

const stores = {
	frameitStore: PersistState,
}

export { stores, FrameItStore, FrameItProvider, FrameItContext, useFrameItStore }
```

where `PersistState` looks like:

```tsx
import {
	persistence,
	useClear,
	useDisposers,
	isSynchronized,
	StorageAdapter,
} from 'mobx-persist-store'

import { FrameItStore } from '@/store/index'

function readStore(name: string) {
	return new Promise<string>((resolve) => {
		const data = localStorage.getItem(name) || '{}'
		resolve(data)
	})
}

function writeStore(name: string, content: string) {
	return new Promise<Error | undefined>((resolve) => {
		localStorage.setItem(name, JSON.stringify(content))
		resolve(undefined)
	})
}

export const PersistState = persistence({
	name: 'FrameItStore',
	properties: ['id', 'trafficSignal', 'padding', 'background', 'shadow', 'image'],
	adapter: new StorageAdapter({
		read: readStore,
		write: writeStore,
	}),
	reactionOptions: {
		// optional
		delay: 2000,
	},
})(new FrameItStore())
```

This isn't working however. Would love to know the solution to this?

**Comment by quarrant** [comment]
check this example https://codesandbox.io/s/fervent-sound-m7ie5?file=/src/App.tsx

**Comment by deadcoder0904** [comment]
So your example is correct but I have a `context.ts` file with:

```tsx
import React from 'react'
import { useLocalObservable } from 'mobx-react'

import { stores, PersistState, FrameItStore } from '@/store/index'

import type { IFrameItStore } from '@/types/index'

export const FrameItContext = React.createContext<IFrameItStore>(new FrameItStore())

export const FrameItProvider = ({ children }: { children: React.ReactChild }) => {
	const frameItStore = useLocalObservable(() => new FrameItStore())

	return <FrameItContext.Provider value={frameItStore}>{children}</FrameItContext.Provider>
}

export const useFrameItStore = () => React.useContext(FrameItContext)
```

Now I have to convert this to use `PersistState` & simply replacing `new FrameItStore()` with `PersistState` isn't working but I'll figure it out :)

Thank you for all the help & the awesome library 🎉

**Comment by deadcoder0904** [comment]
@quarrant if you have any idea of how to provide `PersistState` inside context, then please let me know. Check the above code-block. I have to only change `FrameItContext` to use `PersistState` instead of `new FrameItStore()`.

Currently, it keeps on giving `Uncaught TypeError: Cannot read property 'frameitStore' of undefined` when I converted `PersistState` into a function & called it like `stores.frameItStore`:

```tsx
export const PersistState = () =>
	persistence({
		name: 'FrameItStore',
		properties: ['id', 'trafficSignal', 'padding', 'background', 'shadow', 'image'],
		adapter: new StorageAdapter({ read, write }),
		reactionOptions: {
			// optional
			delay: 2000,
		},
	})(new FrameItStore())
.
.
.
export const FrameItContext = React.createContext<IFrameItStore>(stores.frameitStore())
```

How should I use `PersistState` with Context? Even without making it a function, it still gives error :(

**Comment by quarrant** [comment]
@deadcoder0904 

I don't understand why you are trying to use them together. This is a weird way to use mobx....

**Comment by deadcoder0904** [comment]
@quarrant I just wanted to use Mobx Store in functional components & a MobX maintainer said you can use a hook without having to use a Provider. So that's why I changed it to this. Earlier, I was using a Provider.

But what's the problem in that? It worked fine & Mobx maintainer recommended it to me because of some reason that I don't remember & I can't find a link to it.

Can we not get this to work somehow? Otherwise, I would have to change a lot of my code, sadly :(

**Comment by deadcoder0904** [comment]
The weird part is the counter example works in Codesandbox → https://codesandbox.io/s/mobx-persist-store-4l1dm

So Idk what's wrong with my code which is scarily similar 😂

**Comment by deadcoder0904** [comment]
I think it isn't working because I am using it in Chrome Extension where I have to use `chrome.storage.local.set()` API instead of `localStorage.setItem()` API.

But I can't get `write` function to get called. I mean I do `console.log` in `read` function & it works but `write` doesn't get called. 

```tsx
const read = (name: string): Promise<string> =>
	new Promise((resolve) => {
		chrome.storage.local.get(name, function (data) {
			console.log('read')
			resolve(JSON.stringify(data))
		})
	})

const write = (name: string, content: string): Promise<Error | undefined> => {
	console.log('write')
	return new Promise((resolve) => {
		chrome.storage.local.set({ name: content }, function () {
			console.log('set')
		})
		resolve(undefined)
	})
}
```

Is there anything wrong with it? @quarrant 

This makes the `read` function to return empty `{}`.

**Comment by deadcoder0904** [comment]
Calling `writeInStorage` directly calls the above `write` function but it doesn't call when I put it inside `persistence` so I'm pretty sure the error lies here somewhere as it doesn't set anything in LocalStorage so it can't get anything from LocalStorage.

```tsx
const s = new StorageAdapter({ read, write })
s.writeInStorage('FrameItStore', '{b: 1}')
	.then((w) => {
		console.log({ w })
	})
	.catch((e) => console.error(e))
```

Would love to know if there's anyway to debug `write`?
