### ISSUE TITLE
Consider renaming useClear and useDisposers to distinguish from React hook

### ISSUE THREAD

**Issue by codeBelt** [quarrant/mobx-persist-store#17]
Great library!

I am a React/MobX user and there is a naming convention where React Hooks start with `use`. Please consider renaming `useClear` and `useDisposers` to distinguish from React hook.

The MobX team has done this with `useStaticRendering` and renamed it to `enableStaticRendering`.

> Deprecate useStaticRendering in favor of renamed enableStaticRendering to distinguish from React hook.
https://github.com/mobxjs/mobx-react-lite/pull/302

Some suggests:
- `useClear` -> `clearPersist`
- `useDisposers` -> `stopPersist`

**Comment by quarrant** [comment]
@codeBelt Thank you! Good point! I thought about it
