### ISSUE TITLE
Fix needed to readme to readStore

### ISSUE THREAD

**Issue by MaRaSu** [quarrant/mobx-persist-store#21]
I also made earlier a mistake of doing JSON parse & stringify in my customer StorageAdapter read & write function before noticing it a few days ago when I switched to Typescript and got the warnings...

#16 already fixed the readme for write function. Should do the same for the read function? 

BTW great little library!

**Comment by quarrant** [comment]
@MaRaSu no, the mistake was only in read function

**Comment by MaRaSu** [comment]
@quarrant we probably mean the same thing...I just wanted to say that readme examples should be corrected also for the readStore function, to complement the fix that you did in issue #16,

**Comment by quarrant** [comment]
yes, I'll fix it. 

Thank you! =)
