### ISSUE TITLE
Add a `startPersist` to restart after `stopPersist` is called?

### ISSUE THREAD

**Issue by codeBelt** [quarrant/mobx-persist-store#25]
I don't have a use case right now but I was thinking if you can `stopPersist` it might be nice if you could call `startPersist`. This will allow you to disable and enable saving the data. What do you think?

**Comment by quarrant** [comment]
@codeBelt something like this, see the PR

**Comment by codeBelt** [comment]
@quarrant I don't see it working. I created a example with your modified files:
https://codesandbox.io/s/mobx-persist-store-with-mobx-6-startpersist-33mwc?file=/src/stores/User.store.ts

**Comment by quarrant** [comment]
Ups =)

**Comment by quarrant** [comment]
> @quarrant I don't see it working. I created a example with your modified files:
> https://codesandbox.io/s/mobx-persist-store-with-mobx-6-startpersist-33mwc?file=/src/stores/User.store.ts

it works now

**Comment by codeBelt** [comment]
It's still not working for me. I updated my example with the file change you made but I don't know how it works for you?

![animation](https://user-images.githubusercontent.com/2893563/110654883-27e64280-8184-11eb-8d6a-8b4bf23a9812.gif)

**Comment by quarrant** [comment]
@codeBelt fix it

**Comment by codeBelt** [comment]
Ok, I updated my example and it works now!
