### ISSUE TITLE
Need to wrap app in Provider in mobx 6?

### ISSUE THREAD

**Issue by idanlevi1** [quarrant/mobx-persist-store#38]
I moved to mobx 6v & mobx-react 7v
and I want to ask if I need to wrap root node in Provider like before:
```
<Provider {...stores}>
      <Router>
        <Switch>
          <Route path='/' exact component={RootComponent} />
        </Switch>
      </Router>
</Provider>
```

for example

> "mobx": "^6.1.8",
> "mobx-persist-store": "^0.5.30"
> "mobx-react": "^7.1.0"

**Comment by codeBelt** [comment]
In relation to `mobx-persist-store` it doesn't matter if you use a `Provider` wrapper or not. Are you having issues with data persisting?

**Comment by idanlevi1** [comment]
> In relation to `mobx-persist-store` it doesn't matter if you use a `Provider` wrapper or not. Are you having issues with data persisting?

Do you think the question should be to `mobx` github issues?

**Comment by codeBelt** [comment]
> Do you think the question should be to `mobx` github issues?

Yes, I think it is a `mobx` github question but check out my MobX example for some ideas https://github.com/codeBelt/mobx-local-global-stores

**Comment by codeBelt** [comment]
@quarrant this issue can be closed
