### ISSUE TITLE
What the best practice to check if all store local storage data is hydrate?

### ISSUE THREAD

**Issue by idanlevi1** [quarrant/mobx-persist-store#39]
I use `isSynchronized` to know if the persist data are hydrate
I have a multi-stores and I don't see any example or information about `isSynchronized` in multiple stores

```
import React from 'react';
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom'
import { Provider, observer } from 'mobx-react';
import { GameStore, UserStore } from './stores'
import RootComponent from './RootComponent';
import { isSynchronized } from 'mobx-persist-store';

const stores = { GameStore, UserStore };


const App = observer(() => {
  console.log("App")

  if (!isSynchronized(stores.GameStore) || !isSynchronized(stores.UserStore)) {
    return <p>Loading...</p>;
  }

  return (
    <Provider {...stores}>
      <Router>
        <Switch>
          <Route path='/' exact component={RootComponent} />
        </Switch>
      </Router>
    </Provider>
  );
})

export default App;
```

I used:
> "mobx": "^6.1.8",
> "mobx-persist-store": "^0.5.30"
> "mobx-react": "^7.1.0"

**Comment by quarrant** [comment]
you are right `isSynchronized` not working with multiple stores, but your example is correctly

**Comment by idanlevi1** [comment]
> you are right `isSynchronized` not working with multiple stores, but your example is correctly
@quarrant 
What about one synchronic function that returns when all list of stores are hydrate? it can save a lot of renders
