### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by selvaAiKnow** [quarrant/mobx-persist-store#4]
Hi,
When am running the npm test am getting error like this 

 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import StorageAdapter from './StorageAdapter';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import {observable, action, decorate} from 'mobx';
    > 2 | import { persistence, useClear, StorageAdapter } from 'mobx-persist-store';
        | ^
      3 | import { readPersist, writePersist } from '../libraries/LocalStorage';
      4 | 
      5 | class AppConfig {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)

Using
"mobx": "^5.15.4",
"mobx-persist-store": "^0.4.4",
"mobx-react": "^6.1.8",
"react": "^16.12.0"

Can you please help me.

**Comment by quarrant** [comment]
Are you using `skipLibCheck` option?

**Comment by selvaAiKnow** [comment]
Are you asking in unit test code right?

We are not using in unit test place.

**Comment by quarrant** [comment]
I adding a commonjs build. Version 0.4.10

**Comment by selvaAiKnow** [comment]
Can you please explain?

**Comment by quarrant** [comment]
Yes, update version

**Comment by selvaAiKnow** [comment]
Thank you, It's working
