### ISSUE TITLE
problem with saving refs 

### ISSUE THREAD

**Issue by morelgarisi** [quarrant/mobx-persist-store#40]
after mooving to this package from mobx- persist to get support for mobx 6 
keep getting this error:
![Screen Shot 2021-04-13 at 17 35 38](https://user-images.githubusercontent.com/18554479/114570734-bfa4e800-9c7e-11eb-9627-e3419b6cb3c0.png)
my persisiance func:
export const persistStore = (target, properties, persistName) => {

    return persistence({
        name: persistName,
        properties,
        adapter: new StorageAdapter({
            read: async (name) => {
                const data = window.localStorage.getItem(name);
              console.log("[Mobx] persistStore [Read] target:", target._storageName, 'name:', name, 'data:', data)
                return data ? JSON.parse(data) : undefined;
            },
            write: async (name, content) => {
            console.log("[Mobx] persistStore [Write] target:", target._storageName, 'name:', name, 'content:', content)
                window.localStorage.setItem(name, JSON.stringify(content));
            }
        }),
        reactionOptions: {
            delay: 200
        }
    })(target);
};

the store:
import { observable, makeAutoObservable, toJS } from "mobx";
import { clearPersist, stopPersist, startPersist } from "mobx-persist-store";
import { persistStore } from '../mobxutils/utils'
import { isSynchronized } from 'mobx-persist-store';

class DataStore {
 

    alertSessionRef = null;
    alertSessionVisible = false;
  

    constructor() {
        makeAutoObservable(this);
      
        persistStore(this, [
            'alertSessionRef',
            'alertSessionVisible',
            'session_time',
            'time_before_seesion_end',
            'alertRef',
            'alertVisible',
            'modalInAir'

        ],
            'DataStore');
    }

    stopPersist() {
        stopPersist(this);
      }
    
      startPersist() {
        startPersist(this);
      }

   
    get isSynchronized() {
        console.log('user store',isSynchronized(this))
        return isSynchronized(this)
      }
 
   

    setAlertRef(alertRef) {
        this.alertRef = alertRef;
    }

    
    setAlertSessionRef(alertRef) {
        this.alertSessionRef = alertRef;
     console.log('alertRef', this.alertSessionRef )

        if (UserStore.isAuth) {
            if (this.alertSessionRef) {
                this.alertSessionRef.openModal();
            }
        }
    }

    setAlertSessionInVisible() {
        this.alertSessionVisible = false;
    }

    showSessionAlert() {
        this.alertVisible = false;
        this.alertSessionVisible = true;
    }

   
    setAlertInVisible() {
        this.alertVisible = false;
    }

  
    onModalHide() {
        this.modalInAir = false;
    }

 
    async showAlert(info) {
        while (true) {
            if (!this.modalInAir) {
                this.modalInAir = true;
                if (this.alertRef) {
                    this.alertRef.openModal(info);
                    this.alertVisible = true;
                }

                break;
            } else {
                await new Promise((resolve, reject) => {
                    setTimeout(() => resolve(), 350);
                });
            }

        }
    }

 
  

}

export default new DataStore();

the refs :

  render() {
    return (
      <Router history={this.props.history}  >
            <SessionModal
          ref={(divElement) => {  this.props.DataStore.setAlertSessionRef(divElement) }}
        /> 
        <AlertModal
          ref={(ref) => { 
            this.props.DataStore.setAlertRef(ref) }}
        />
        <Switch>
        <Route exact path="/login" component={Loggedin} />
        <Route exact path="/login/*" component={Loggedin} />
        <Route exact path="/reset-password/:token" component={ResetePass} />
          <AuthCheck exact path='/app/*' component={App} />
          <AuthCheck exact path='/app' component={App} />

          <Route exact path ='/' render={()=><Redirect to='/app'/>}/>
          <Route render={()=><PageNotFound/>}   />
        
       

        </Switch>
     
      </Router>
    );
  }

**Comment by codeBelt** [comment]
@morelgarisi 

- We are working on v1.0 
https://github.com/quarrant/mobx-persist-store/tree/issue-36/stable-release
- Check out the example for v1.0 
https://codesandbox.io/s/mobx-persist-store-version-1-f852w?file=/src/stores/User.store.ts

Let me know if how this new version works for you
