### ISSUE TITLE
makePersistable is not saving an ES6 Map to the local storage correctly. Possible solution in the comment.

### ISSUE THREAD

**Issue by BornaGajic** [quarrant/mobx-persist-store#41]
Hi!
I'm using **Typescript** and ran into a problem where `makePersistable` wouldn't save a `Map` properly to local storage e.g. content would be empty - `{}`.
With a little digging, I found that in the `StorageAdapter.js` content is being stringified without the use of the `replacer` function for `JSON.strigify` method which led to the problem.

Consider a possible working solution for JS:

![image](https://user-images.githubusercontent.com/21183212/117456519-92c7b600-af48-11eb-8125-b98c702cd8da.png)
_node_modules\mobx-persist-store\lib\StorageAdapter.js_

Maybe add an option in makePersistable to pass in a replacer function for JSON stringify

**Comment by codeBelt** [comment]
Thanks for the feedback. I will have to look at this later but try setting `stringify: false,` to see if that fixes the issue for now.

https://github.com/quarrant/mobx-persist-store/tree/issue-36/stable-release#storageoptions--reactionoptions

Also here is the example I am working on for v1.0 of mobx-persist-store: 
https://codesandbox.io/s/mobx-persist-store-version-1-f852w

**Comment by codeBelt** [comment]
For now you can create your own storage adapter to handle your situation:

```ts
makePersistable(this, {
  name: 'SampleStore',
  properties: ['someProperty'],
  storage: {
    setItem: () => {
      // Add a customizes version of window.localStorage.setItem to handle Map
      // return window.localStorage.setItem;
    },
    removeItem: window.localStorage.removeItem,
    getItem() {
      // Add a customizes version of window.localStorage.getItem if needed
      return window.localStorage.getItem;
    },
  },
});
```

I found this article https://2ality.com/2015/08/es6-map-json.html

**Comment by codeBelt** [comment]
@BornaGajic I am curious what you come up with for your custom storage adapter to solve this issue. If you could, create a codesandbox example and share here.

**Comment by codeBelt** [comment]
You need to update your `getItem` to hand converting the data back into a Map object:

```ts
getItem: (key: string) => {
  let data: any = window.localStorage.getItem(key);

  data = JSON.parse(data as string);

  const strMap = new Map();

  for (const k of Object.keys(data.myMap)) {
    strMap.set(k, data.myMap[k]);
  }

  return {
    ...data,
    myMap: strMap,
  };
}
```

The code is ugly but hopefully you can see how to do it.

**Comment by BornaGajic** [comment]
Thanks @codeBelt 
I've managed to solve my second issue.

Here's the final codesandbox: 
https://codesandbox.io/embed/mobx-persist-store-map-bug-forked-bfk1q?fontsize=14&hidenavigation=1&theme=dark

Not the best implementation but I'll leave it for now like this.
Currently, my code depends on `modelMap` which storages classNames and new instances of that class. I'm checking if there's a class with the same name as the key of the JSON object - if there is, assign all children to that class instance, if not then create a Map from it.
