### ISSUE TITLE
PersistStore is not return promise so it not possible to wait it

### ISSUE THREAD

**Issue by zr9** [quarrant/mobx-persist-store#47]
Currently `PersistStore` is not return Promise so it not possible to wait for `makePersistable`.
In that case state will be updated once it loaded from storage and it cause unneeded render.
Can be avoided if we return `this.init()` from `makePersistable`.
I can make pull request if help

**Comment by codeBelt** [comment]
Sure, open to you making a pull request. Could you create a codesandbox example showing the issue? I am not 100% clear on the issue.

**Comment by codeBelt** [comment]
@zr9 there is [isHydrated](https://github.com/quarrant/mobx-persist-store#ishydrated) to let you know when the store has been updated.

**Comment by zr9** [comment]
@codeBelt 
Sure, will update.
Yup for update yes, but for initialization nope.
If you have loader component which initialize store and make it persistable.
In that case when you make it persistable it will load previous state if exist, then update state. That load/update will trigger render

**Comment by zr9** [comment]
@codeBelt 
Here we go [Example](https://codesandbox.io/s/mobx-render-on-load-bug-b866m?file=/src/index.js)

**Comment by codeBelt** [comment]
I am not sure making `makePersistable` a Promise will work for what you are trying to do. I could be wrong and open to see a PR for it. Are you thinking something like this:

```ts
const init = async() => {
  const initialState = observable({
    endTime: 0,

    setEndTime(val) {
      this.endTime = val;
    }
  });

  await makePersistable(initialState, {
    name: "UserStore3",
    properties: ["endTime"],
    storage: window.localStorage
  });

  return initialState;
};
```


Will this work fo you:

```ts
const init = () => {
  console.log("init rendered");

  const initialState = observable({
    endTime: 0,

    get isHydrated() {
      return isHydrated(this);
    },

    setEndTime(val) {
      this.endTime = val;
    }
  });

  makePersistable(initialState, {
    name: "UserStore3",
    properties: ["endTime"],
    storage: window.localStorage
  });

  return initialState;
};

export const Loader = observer(({ children }) => {
  const [vars] = useState(() => init());

  if (vars.isHydrated === false) {
    return null;
  }

  return children({ state: vars });
});
```
https://codesandbox.io/s/mobx-render-on-load-bug-forked-y2te2?file=/src/index.js

**Comment by rafaeldsousa** [comment]
@zr9 have you created a PR for this one ? I'm also after an await for `makePersistable`. 
@codeBelt with mobx-persist, we're able to create the store and have a `then`.
E.g.

```js
import { create } from 'mobx-persist';
import localForage from 'localforage';

hydrate = create({
        jsonify: false,
        storage: localForage
});
hydrate(appStorageName, appStore).then(() => {
    appStore.hydrated = true;
    if (process.env.NODE_ENV === 'development') {
        console.log(appStorageName + ' hydrated');
    }
});
```

Would your suggested implementation above do the same as this ?

**Comment by codeBelt** [comment]
@rafaeldsousa PR here: https://github.com/quarrant/mobx-persist-store/pull/49

**Comment by codeBelt** [comment]
@zr9  make sure you call [stopPersisting](https://github.com/quarrant/mobx-persist-store#stoppersisting) so `makePersistable` doesn't continue holding on to the store that was passed in.

```js
export const Loader = observer(({ children }) => {
  const [localStore] = useState(() => store());

  useEffect(() => {
    // Called when the component is unmounted
    return stopPersisting(localStore);
  }, [localStore]);

  if (localStore.isHydrated === false) {
    return null;
  }

  return children({ state: localStore });
});
```
