### ISSUE TITLE
[Demo]: Store Hydrated is always Yes

### ISSUE THREAD

**Issue by deadcoder0904** [quarrant/mobx-persist-store#51]
I am checking out the demo & it's probably the best demo I've seen of any library with an explanation in the demo itself. You might wanna use [Stackblitz](https://stackblitz.com) as it's faster than CodeSandbox.

I am confused as to why **Store Hydrated** is always **Yes**? I checked the code & there's a ternary operator but it never turns to **No**. Why is that?

**Comment by codeBelt** [comment]
If you do `console.log(localStore.isHydrated);` in the demo you will see it will be `false` and then `true`. It happens very fast.

I created a new demo that delays the `getItem` and now you can see it changing.

https://codesandbox.io/s/mobx-persist-store-customized-storage-go767?file=/src/stores/User.store.ts

```ts
...

const customizedStorageController = {
  setItem: (key: string, data: any) => window.localStorage.setItem(key, data),
  removeItem: (key: string) => window.localStorage.removeItem(key),
  getItem: async (key: string) => {
    await delay(milliseconds.seconds(3));

    return window.localStorage.getItem(key);
  }
};

...

makePersistable(this, {
  name: "UserStore",
  properties: ["user"],
  storage: customizedStorageController
});
```

**Comment by deadcoder0904** [comment]
Oh, cool. Got it. And does rehydrate store mean it stores the data into **localStorage**? I did read the docs but don't completely understand the term?

Also, why doesn't **Clear Store Persist** button turn the **Store Persisting** to **Off**?

Bdw, a little nitpick if you want to improve the demo: CDN link to Semantic UI is slow so it shows HTML without styles. You might wanna keep it in the sandbox itself :)

**Comment by codeBelt** [comment]
The button "Rehydrate Store" (I just changed it to "Hydrate Store") will grab what is in **localStorage** and update the MobX store.

The way I have the "Clear Store Persist" button setup is to delete what is in **localStorage** with `clearPersistedStore`. I have the "Pause Store Persist" call `pausePersisting` and that will turn the Store Persisting to Off.

If you want to fork the demo and improve it. I would take the help. Just add the link to this issue.

**Comment by deadcoder0904** [comment]
Cool, got it, thanks. I'll add suggestions the next time I work with `mobx-persist-store` :)
