### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by rafaeldsousa** [quarrant/mobx-persist-store#53]
@codeBelt Any chance we could drop this to "es2015" to support ie11 ? I need ie11 support and currently that isn't happening.

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["ES2015","DOM"],
    "..."
  }
}
```

https://github.com/quarrant/mobx-persist-store/blob/b4d3549582e3ce36f100aa4a9cac19c8edd38d4c/tsconfig.json#L3

**Comment by quarrant** [comment]
@rafaeldsousa try v1.0.3

**Comment by rafaeldsousa** [comment]
@quarrant I think you can keep module as is but you'll need to include both `target` and `lib` in the tsconfig. The es5 and esm2015 files haven't been transpiled in the lib folder and on my testing yesterday I could see that happening if I did not include those in the configs.

```js
"target": "es5",
"lib": ["ES2015","DOM"],
```

**Comment by rafaeldsousa** [comment]
@quarrant ignore comment above, one of the apps in my mono repo was still targeting the earlier release and cause the issue I was having. Can confirm now that it is working on ie11 as expected. 
Thanks a lot for the quick resolution.
