### ISSUE TITLE
`configurePersistable` not apply configuration globally 

### ISSUE THREAD

**Issue by Bort-777** [quarrant/mobx-persist-store#56]
Looks like `configurePersistable` don't apply storage property for all stores. 

Example (28th line show that `makePersistable` work well):
https://snack.expo.io/@azfinstek/sandbox-react-native

**Comment by codeBelt** [comment]
In you code I don't see anything calling `setupPersistable` which is why I think `configurePersistable` is not being setup correctly.

**Comment by Bort-777** [comment]
Yeah, my issue. Anyway in my code I found other corner case, I export mobx store class like singleton, but tried to call `configurePersistable` on root node after all imports.
Cool, thank you for lib
