### ISSUE TITLE
How to support data versioning?

### ISSUE THREAD

**Issue by ducNgbk** [quarrant/mobx-persist-store#59]
Hi, how can I support versioning of my data?

For example
```typescript
makePersistable(
      this,
      {
        storage: AsyncStorage,
        name: this.PersistKey,
        properties: ['listData'],
        version: 1.0.0,
      },
      {delay: 100, fireImmediately: false},
    );
```

then in future, I increase **1.0.0** to **1.1.0**, my persisted properties will be initialized again (not getting data from previous version)

I know, this library has 
```typescript
    expireIn: 86400000,
    removeOnExpiration: true,
```
But I don't know exactly when I will change my properties structure

**Comment by kubk** [comment]
What if you just rename the key? Example:
```diff
class Store {
-  persistKey = 'key';
+  persistKey = 'key-1';
}
``` 

Would it work out?

**Comment by quarrant** [comment]
@kubk yep, you'll right

**Comment by ducNgbk** [comment]
@kubk brilliant, thanks very much, you rock it
