### ISSUE TITLE
How to deal with Fast Refresh on React Native?

### ISSUE THREAD

**Issue by SrBrahma** [quarrant/mobx-persist-store#64]
I have makePersistable in my init(), so I can await it, to have the values loaded before moving on.

But, on fast refresh, on React Native, it will trigger a warn that makePersistable was called with the same name.

I have tried using `if (!isPersisting(this))` and then makePersistable, but it won't always work for some reason.

Does anyone have experience and a workaround for this issue?

**Comment by SrBrahma** [comment]
It would be good if there was a function that had the same lines found on

https://github.com/quarrant/mobx-persist-store/blob/b4be7da482423a74bc8d83d206f6904ffdb94178/src/makePersistable.ts#L13-L15

**Comment by SrBrahma** [comment]
![image](https://user-images.githubusercontent.com/28177550/131477168-6fcb4bf8-c8c3-4bef-9c46-cf69aa3d2b83.png)

**Comment by sergeykimaia** [comment]
doing this will make it so isHydrated returns false

**Comment by sergeykimaia** [comment]
> I wonder if these feature will solve your issue? #82

I don't think it's related.
currently in react native after editing code fast refresh will reload the store but not remove the store from PersistStoreMap

```
  constructor() {
    makeAutoObservable(this, {}, { autoBind: true });
    const persist = () => {
      makePersistable(this, {
        name: 'userStore',
        properties: [
          'user',
          'accessTokenBlock'
        ],
        storage: AsyncStorage,
      });
    };
    const persistedStore = Array.from(PersistStoreMap.values()).find((el) =>
      el.storageName.includes('userStore')
    );
    if (persistedStore) {
      persistedStore.stopPersisting();
    }
     persist();
  }
``` 

do you think this is an ok solution?

**Comment by sergeykimaia** [comment]
> When you say "fast refresh" is that the same a React hot reloading? I have noticed during development mode I will get the warning you are get but when I have a product build I don't see the warning and everything works as expected. It might be a development issue and I wouldn't create a work around just to hide the warning. It's a warning and not a error so you can ignore it in dev mode.

yeah its basically the same as React hot reload, I would like to prevent the warning from showing because my 'PersistStoreMap' size quickly grows since I have several stores in my project, and every time I save it adds 4 more into PersistStoreMap

**Comment by codeBelt** [comment]
I wonder if we change the `PersistStoreMap` from a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) to a [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) if that will fix the issue when developing. I can look into this.

@quarrant can you re-open this issue?

**Comment by angelxmoreno** [comment]
@codeBelt @quarrant 
Has there been progress on this?

**Comment by leaftail1880** [comment]
@codeBelt @quarrant any updates?

**Comment by leaftail1880** [comment]
Made this
```ts
import { PersistStoreMap, makePersistable } from 'mobx-persist-store'

// eslint-disable-next-line @typescript-eslint/naming-convention
export const makeReloadPersistable: typeof makePersistable = (
	object,
	options
) => {
	for (const [key, store] of PersistStoreMap.entries()) {
		if (store.storageName === options.name) {
			store.stopPersisting()
			PersistStoreMap.delete(key)
		}
	}
	return makePersistable(object, options)
}
```
