### ISSUE TITLE
Example with functional components?

### ISSUE THREAD

**Issue by 10000multiplier** [quarrant/mobx-persist-store#68]
Hi, 

It seems that all the examples are with class components.

How would you go about getting `mobx-persist-store` to work with a functional component?

Thank you.

**Comment by quarrant** [comment]
Hi!

What it https://github.com/quarrant/mobx-persist-store#demo

**Comment by codeBelt** [comment]
@10000multiplier I think this would work but I never tried it out:

```js
import { observable } from 'mobx';
import { makePersistable } from 'mobx-persist-store';

export const SomeStore = () => {
  const initialState = observable({
    endTime: 0,

    setEndTime(val) {
      this.endTime = val;
    },
  });

  makePersistable(initialState, {
    name: 'SomeStore',
    properties: ['endTime'],
    storage: window.localStorage,
  });

  return initialState;
};
```

**Comment by 10000multiplier** [comment]
@codeBelt thanks! 

Also on an unrelated note, do you happen to know if this library be used with `mobx-state-tree`?

**Comment by codeBelt** [comment]
Never used `mobx-state-tree` but let us know how it works. 

I have my own way of working with MobX https://github.com/codeBelt/mobx-local-global-stores

**Comment by quarrant** [comment]
Heh, it's really simple https://codesandbox.io/s/vibrant-frog-iud38?file=/src/App.tsx

**Comment by 10000multiplier** [comment]
@quarrant wow thanks, just what I needed!

**Comment by 10000multiplier** [comment]
@quarrant is there also a way to do this with `configurePersistable` ?

**Comment by angelxmoreno** [comment]
@10000multiplier look for all instances of `makePersistable` and verify you are not reusing the same name prop

**Comment by angelxmoreno** [comment]
oh wait, you are using react-native. There is some sort of bug that makes hot-reload run certain parts of your code twice. This is not an issue with this lib but hot-reload.

**Comment by 10000multiplier** [comment]
@angelxmoreno aww okay. Sounds like I don't have to worry about it too much then.

**Comment by angelxmoreno** [comment]
@10000multiplier follow #64

**Comment by 10000multiplier** [comment]
@angelxmoreno thanks
