### ISSUE TITLE
mmkv storage support

### ISSUE THREAD

**Issue by negati-ve** [quarrant/mobx-persist-store#73]
Hi, 

Is it possible to support https://github.com/ammarahm-ed/react-native-mmkv-storage ?
on RN, mmkv produces a far superior result than localforage

**Comment by quarrant** [comment]
Why not? You can write yours implementation of interface https://github.com/quarrant/mobx-persist-store/blob/master/src/types.ts#L38

**Comment by Navipro70** [comment]
From `rn-mmkv` docs: [asd](https://github.com/mrousavy/react-native-mmkv/blob/master/docs/WRAPPER_MOBX.md)
But `rn-mmkv-storage` set's values by types, just add typeof condition for set for every type. I don't know is `rn-mmkv-storage` supports getting any non type based value, if isn't, I simply suggest you to use `react-native-mmkv`, or just set and get values with JSON parsing

I hope my info helps you, this issue not exactly related to mobx-persist-store

**Comment by quarrant** [comment]
Show me an example and I'll help you with typings
