### ISSUE TITLE
UnhandledRejection Error

### ISSUE THREAD

**Issue by Rahilkzi** [quarrant/mobx-persist-store#86]
###  NextJs

![16560922659264222399876512734983](https://user-images.githubusercontent.com/44476072/175613490-010cb03f-062d-47fe-a865-c7bc246a0671.jpg)

error - UnhandledRejection: Error: No available storage method found.

**Comment by codeBelt** [comment]
Can you create a [codesandbox](https://codesandbox.io/) example so we can see the issue. This way it will be easier for use to troubleshoot.

**Comment by Rahilkzi** [comment]
> Can you create a [codesandbox](https://codesandbox.io/) example so we can see the issue. This way it will be easier for us to troubleshoot.


### CodeSandBox

[https://codesandbox.io/s/upbeat-visvesvaraya-mm052j?file=/pages/store/TodoStore.js](url)

**Comment by codeBelt** [comment]
@Rahilkzi If you have an app that is Server-side rendering (SSR) you can set the storage value `undefined` to prevent errors.


```ts
const isBrowser = typeof window !== 'undefined';

class TodoStore {
  todos = [];

  constructor() {
    // ...

    makePersistable(this, {
      name: "TodoStore",
      properties: ["todos"],
      storage: isBrowser ? localforage : undefined
    });
  }
```


Also if you are working with MobX and Next.js make sure you are using [enableStaticRendering](https://mobx.js.org/react-integration.html#static-rendering) in your `_app.tsx`.

```ts
import { enableStaticRendering } from 'mobx-react-lite';

const isServer = typeof window === 'undefined'

enableStaticRendering(isServer);
```

Let me know if that fixes the issue.
