### ISSUE TITLE
Warning: Store does not have a valid storage adaptor

### ISSUE THREAD

**Issue by viktorgullmark** [quarrant/mobx-persist-store#96]
Hey! Thanks for the great package. 

Got a pretty annoying warning though after following the examples. Using latest mobx and getting the following:

![image](https://user-images.githubusercontent.com/11405940/203578179-ae70dbc6-b598-4193-806d-1c02924cf703.png)

App.tsx
```
configurePersistable(
  {
    storage: localforage,
    stringify: false,
  },
  { delay: 200, fireImmediately: false },
);

const App = () => {
  return (
    <HashRouter>
      <Routes>
        <Route path='/' index={true} element={Login()} />
        <Route path='/dash' element={Dashboard()} />
      </Routes>
      <MobxRouter />
    </HashRouter>
  );
};
```

AuthStore.ts
```
export default class AuthStore {
  user?: UserDomain;
  code = "";
  authState = uuidv4();

  constructor(private rootStore: RootStore) {
    makeAutoObservable(this);

    makePersistable(this, {
      name: "AuthStore",
      properties: ["user"],
    });
  }
```

It seems strange that these properties are required on a store, am I missing something or is there a way to remove the warning?

Cheers!

**Comment by jwoyame** [comment]
You specify your storage as:

```javascript
storage: localforage,
```

Is that a typo?

Depending on what type of storage class this is, the issue may be resolved by #104.
